### ISSUE TITLE
fix: A blank white page is displayed when navigate to the Access Managment page using URL

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#135] opened 2024-08-30 15:22 UTC
### Describe your issue

An empthy white page is shown when attempling to open Access Managment page using page url. The White page is displayed for both Authorized and Unauthorized users.

### Steps to reproduce

Pro-condition: User is registered. Login with valid credentials.

1. Navigate to the Access Managment page using side bar
2. Copy the page URL 
3. Open the copied link in a New tab
4. Observe the page appearance

### What was the actual result?

The white blank page is shown.

### What was the expected result?

The Access Managment page is shown with its content.

### Put here any screenshots or videos (optional)

1. https://github.com/user-attachments/assets/7a3a1d1b-525b-4133-a1f7-66c1b1a647b1

2. (The same with Unauthorized user) 
https://github.com/user-attachments/assets/c4228b02-d26b-45a5-9059-3a3f26243568

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Critical (S2)

**Comment by VeronikaHordus** [comment] 2024-08-30 15:23
(For QA) After the fix - check the Route Protection for the Access Managment page.

**Comment by GvoFor** [comment] 2024-09-03 08:45
I just noticed that this is the same issue, as #145. @liza-veis check my [PR](https://github.com/BinaryStudioAcademy/bsa-2024-gitfit/pull/161) with fix of mentioned issue

**Comment by liza-veis** [comment] 2024-09-03 11:28
@GvoFor it's a bit another issue, the problem here is the routing on deployment. After a non-root page reloads, it doesn't navigate the user back to the app, so it displays a permanent white screen. Currently, there is a small fix that prevents this behavior, so it's not reproducible anymore on deployment, but I would keep this issue because it should be fixed by another update.

**Comment by AnnaRomaniuta** [comment] 2024-09-26 15:49
Everything looks good now!

**Closed** 2024-09-26 15:49 UTC
Labels: bug
